# Penalty parameter alpha (used for initialization if adaptive alpha)
alpha : 1
# Adaptive parameters : must be set to nothing, alpha, or both (which means alpha and tau)
#adaptive : nothing
#adaptive : alpha
adaptive : both
# Factor to balance primal and dual residual in adaptive alpha computation
mu : 2.
# Factor to multiply alpha in adaptive alpha computation (used for initialization if adaptive alpha and tau)
tau : 2.
# Factor to balance primal and dual residual convergence speed in adaptive tau computation
xi : 1.
# Maximum value of the factor to multiply alpha in adaptive alpha and tau computation
tau_max : 100.
# Error value for a stopping criterion based on small residuals. 0 means no stopping criterion
stoppingCriterionValue : 0
# Boolean to save (or not) sinograms u and v at same iterations as the image
saveSinogramsUAndV : false
