# AML needs an initial image value strictly higher than the bound
initial image value : 1.
# The denominator threshold is used to avoid division by 0
denominator threshold : 1e-10
# The lower bound of the AML algorithm (if positive, it is interpreted as -infinity)
bound : 0.
